version: '3.8'


services:
  service:
    build: ./
    container_name: monitoring
    command: poetry run python main.py
    env_file: ./.env
    restart: always
    volumes:
      - /root/logs/MONITORING/panel:/code/logs/
    networks:
      - GLOBAL_NETWORK


networks:
  GLOBAL_NETWORK:
    external: true
